const randomantwoorden = [
    "Echt waar?",
    "Weet je dat zeker?",
    "Wie weet...",
    "Interessant...",
    "Ik weet het niet of ik er mee eens ben...",
    "Zeker weten!",
    "Misschien",
    "Wat bedoel je daarmee?",
    "Wat wil je daarmee zeggen?",
    "Je hebt waarschijnlijk gelijk.",
    "Onzin! Klopt niets van.",
    "Trouwens, wat was je morgen van plan te doen?",
    "Dat is precies wat ik dacht.",
    "Dat is tegenwoordig een populaire mening.",
    "Dat hoor ik tegenwoordig wel vaker.",
    "Prachtig!",
    "Daar kon je weleens spijt van krijgen.",
    "Denk je dat echt?",
    "Inderdaad...",
    "Dat bedoel ik!",
    "Wie weet..."
];

const chatwoordenboek = {
    "blij": "Ik ben vandaag ook blij.",
    "verdrietig": "Je geraakt er wel uit.",
    "computer": "Computers veroveren de wereld! Je praat er zelfs met één!",
    "muziek": "Heb je het nieuwe album van Lana Del Ray gehoord?",
    "kunst": "Maar wat is kunst nu eigenlijk?",
    "grap": "Ik ken maar één grap: wat doet een plastische chirurg? Patiënten een oor aannaaien",
    "javascript": "Ik hou van programeren!!!",
    "dom": "Ik ben niet dom! Mijn grap(pen) zijn beter dan die van Siri...",
    "weer": "Ik vraag me af of het morgen zonnig zal zijn.",
    "jij": "Houd mij erbuiten!",
    "zeker": "Hoe kun je nu zo zelfverzekerd zijn?",
    "praten": "Praatjes vullen geen gaatjes! Doe iets!",
    "denk": "Maar je kunt ook teveel nadenken",
    "hallo": "Hoe gaat het ermee?",
    "dragen": "Ik draag geen kleren. Ik heb niet eens een verpakking."
};